### ISSUE TITLE
Tried to install - not working

### ISSUE THREAD

**Issue by edanisko** [wehaa/inline-field-update#1]
$composer require wehaa/inline-field-update
 
[InvalidArgumentException]                                                                                                                 Could not find a matching version of package wehaa/inline-field-update. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (dev).  

Laravel 5.7.28
Nova 1.3.2

**Comment by ajarti** [comment]
Hi @edanisko,

If you look in composer.json the package is actually "wehaa/liveupdate",  that installs fine.

Enjoy.

**Comment by msassa** [comment]
Sorry, I start the project with a wrong name package and this is the result.
I already update the docs, I hope I can change the entire package name soon.

Like @edanisko say, you can install the package using `composer require wehaa/liveupdate`
