### ISSUE TITLE
Feature request: Minimum width 

### ISSUE THREAD

**Issue by albalooshi** [wehaa/inline-field-update#2]
![image](https://user-images.githubusercontent.com/13213888/56862615-75ed6500-69b5-11e9-96a0-6d6025ea4b02.png)

It would be great if we can specify a Minimum width for the input, as when the row is filled with data it doesn't get very short.

**Comment by didix16** [comment]
Is this feature implemented yet? I'm having the same problem and I cannot change the width...

**Comment by msassa** [comment]
You can do it and send a PR. Thanks
