### ISSUE TITLE
Bug: Ignores validations

### ISSUE THREAD

**Issue by jhm-ciberman** [wehaa/inline-field-update#3]
I have:

```php
            Liveupdate::make(__('Delivered Quantity'), 'delivered_quantity')
                ->rules('nullable', 'number', 'lte:quantity')
                ->sortable(),
```

But it ignores the validations

**Comment by KevinKodamera** [comment]
I have encountered this as well.
However i would consider this a bug.

**Comment by PatricNox** [comment]
Yep, this is a bug.
I have the very same issue which is formed as a bug, not enhancement, for my project.

**Comment by PatricNox** [comment]
@msassa Could you assist?

**Comment by msassa** [comment]
Hi @PatricNox 
I'm really short of time right now. But I can accept a PR if anyone can fix this.
Sorry.

**Comment by KevinKodamera** [comment]
I've created a patch for v0.1.

[validation.txt](https://github.com/wehaa/inline-field-update/files/3879198/validation.txt)
